name: ClearML Checks
on:
  [push]

jobs:
  model-training:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ClearML
        run: |
          python -m pip install --upgrade pip clearml pandas tabulate github3.py Jinja2
          pip install -r ml-models/requirements.txt
      - name: Start the task
        id: launch_task
        run: |
          python ml-models/train_bagging.py


  release-model:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ClearML
        run: |
          python -m pip install --upgrade pip clearml
          sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Start the task
        id: launch_task
        run: |
          clearml-serving --id c0282de094604bc3aec22a6778473043 model add --engine sklearn --endpoint "cloud_cost_predict" --preprocess "inference_preprocess.py" --name "Bagging Tree Regressor Training - cost-model" --project "NCI-ML-Project"